name: Build Xelph ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write
    container:
      image: archlinux:latest
      options: --privileged
      
    steps:
      - uses: actions/checkout@v2
      
      - name: Set current date as environment variable
        run: echo "DATE=`date +'%Y.%m.%d'`" >>$GITHUB_ENV

      - name: Update packages and install archiso
        run: pacman -Syu --noconfirm archiso mkinitcpio-archiso git squashfs-tools

      - name: Build ISO
        run: |
             pacman -S --noconfirm --needed archlinux-keyring wget
             # Chaotic AUR
             echo "Fetching chaotic keys"
             pacman-key --init && pacman-key --recv-key 0706B90D37D9B881 FBA220DFC880C036 --keyserver keyserver.ubuntu.com && pacman-key --lsign-key 0706B90D37D9B881 FBA220DFC880C036 && pacman --noconfirm -U 'https://geo-mirror.chaotic.cx/chaotic-aur/chaotic-'{keyring,mirrorlist}'.pkg.tar.zst' && echo "[multilib]" >> /etc/pacman.conf && echo "Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf && echo "[chaotic-aur]" >> /etc/pacman.conf && echo "Include = /etc/pacman.d/chaotic-mirrorlist" >> /etc/pacman.conf
             pacman-key --populate archlinux chaotic
             mkarchiso -v -w ./work -o ./out ./archiso/
             echo "ISO Built in ./out folder!"
             
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.DATE }}
          prerelease: false
          title: "Xelph"
          files: |
            out/*
